views:
  - title: Home
    cards:
      - type: vertical-stack
        cards:
          - type: thermostat
            entity: climate.gf_thermostat
            name: Must use heat button below.
          - type: horizontal-stack
            cards:
              - show_name: true
                show_icon: true
                type: button
                tap_action:
                  action: toggle
                entity: switch.pump_status
                name: Pump
              - type: vertical-stack
                cards:
                  - show_name: false
                    show_icon: true
                    type: button
                    tap_action:
                      action: toggle
                    entity: button.up
                  - show_name: false
                    show_icon: true
                    type: button
                    tap_action:
                      action: toggle
                    entity: button.set
                    icon: ''
                  - show_name: false
                    show_icon: true
                    type: button
                    tap_action:
                      action: toggle
                    entity: button.down
              - show_name: true
                show_icon: true
                type: button
                tap_action:
                  action: toggle
                entity: switch.heat_power
                name: Heat
title: Grainfather
